package com.color.picker.colornamepicker.util;

import com.color.picker.colornamepicker.model.ColorModel;

import java.util.ArrayList;

public class Util {


    public static ArrayList<ColorModel> colorList() {
        ArrayList<ColorModel> colorList = new ArrayList<ColorModel>();

        colorList.add(new ColorModel("Red Color", "#FF0000"));
        colorList.add(new ColorModel("Imperial Red Color", "#ED2939"));
        colorList.add(new ColorModel("Folly Color", "#FF004F"));
        colorList.add(new ColorModel("Persian Color", "#CA3433"));
        colorList.add(new ColorModel("Strawberry Color", "#FB2943"));
        colorList.add(new ColorModel("Carmine Color", "#FF0040"));
        colorList.add(new ColorModel("Alizarin Crimson Color", "#E32636"));
        colorList.add(new ColorModel("Neon Red Color", "#FF073A"));
        colorList.add(new ColorModel("Cardinals Red Color", "#BD2031"));
        colorList.add(new ColorModel("Bright Red Color", "#FF000D"));
        colorList.add(new ColorModel("Candy Apple Red Color", "#FF0800"));
        colorList.add(new ColorModel("Crimson Color", "#B80F0A"));
        colorList.add(new ColorModel("Carmine Red Color", "#FF0038"));
        colorList.add(new ColorModel("Electric Crimson Color", "#FF003F"));
        colorList.add(new ColorModel("Ferrari Color", "#FF2800"));
        colorList.add(new ColorModel("Maroon Color", "#800000"));
        colorList.add(new ColorModel("Crayola Red Color", "#EE204D"));
        colorList.add(new ColorModel("Orange Red Color", "#FF2400"));
        colorList.add(new ColorModel("Scarlet Color", "#FF2400"));
        colorList.add(new ColorModel("Cincinnati Red Color", "#C6011F"));
        colorList.add(new ColorModel("Raspberry Color", "#D21F3C"));
        colorList.add(new ColorModel("Fire Engine Red Color", "#FE0002"));
        colorList.add(new ColorModel("Harvard Crimson Color", "#A51C30"));
        colorList.add(new ColorModel("Ruddy Color", "#FF0028"));
        colorList.add(new ColorModel("Amaranth Red Color", "#F4364C"));
        colorList.add(new ColorModel("Cherry Red Color", "#F7022A"));
        colorList.add(new ColorModel("Auburn Red Color", "#A52A2A"));
        colorList.add(new ColorModel("Spanish Red Color", "#E60026"));
        colorList.add(new ColorModel("Rose Madder Color", "#E32636"));
        colorList.add(new ColorModel("Cherry Color", "#CF0234"));
        colorList.add(new ColorModel("Carmine Color", "#960018"));
        colorList.add(new ColorModel("Rosso Corsa Color", "#D40000"));
        colorList.add(new ColorModel("Rubine Red Color", "#D10056"));
        colorList.add(new ColorModel("Boston University Red Color", "#CC0000"));
        colorList.add(new ColorModel("Ruby Color", "#CA0147"));
        colorList.add(new ColorModel("Red Tape Color", "#B3002F"));
        colorList.add(new ColorModel("Bright Red Color", "#B10000"));
        colorList.add(new ColorModel("Smashing Color", "#AD0020"));
        colorList.add(new ColorModel("Poppy Color", "#AC0019"));
        colorList.add(new ColorModel("Cranberry Color", "#9E003A"));
        colorList.add(new ColorModel("Lipstick Red Color", "#C0022F"));
        colorList.add(new ColorModel("Rose Red Color", "#BE013C"));
        colorList.add(new ColorModel("Monza Color", "#C7031E"));
        colorList.add(new ColorModel("Venetian Red Color", "#C80815"));
        colorList.add(new ColorModel("Vermillion Color", "#F4320C"));
        colorList.add(new ColorModel("Lava Color", "#CF1020"));
        colorList.add(new ColorModel("Red Pepper Color", "#BB112A"));
        colorList.add(new ColorModel("Knock Out Color", "#C81641"));
        colorList.add(new ColorModel("Lust Color", "#E62020"));
        colorList.add(new ColorModel("Firebrick Color", "#B22222"));
        colorList.add(new ColorModel("Rufous Color", "#A81C07"));
        colorList.add(new ColorModel("Brick Red Color", "#8F1402"));
        colorList.add(new ColorModel("Scarlett Color", "#950015"));
        colorList.add(new ColorModel("Blood Red Color", "#980002"));
        colorList.add(new ColorModel("Wine Color", "#722F37"));
        colorList.add(new ColorModel("Sangria Color", "#5E1914"));



        colorList.add(new ColorModel("Merlot Color", "#831923"));
        colorList.add(new ColorModel("Burgundy Color", "#800020"));
        colorList.add(new ColorModel("Maroon Color", "#800000"));
        colorList.add(new ColorModel("Bordeaux Color", "#7B002C"));
        colorList.add(new ColorModel("Blood Color", "#770001"));
        colorList.add(new ColorModel("Salsa Color", "#770C25"));
        colorList.add(new ColorModel("Cedar Wood Finish Color", "#711A00"));
        colorList.add(new ColorModel("Claret Color", "#680018"));
        colorList.add(new ColorModel("Burnt Crimson Color", "#65000B"));
        colorList.add(new ColorModel("Castro Color", "#52001F"));
        colorList.add(new ColorModel("Mahogany Color", "#4A0100"));

        colorList.add(new ColorModel("Blush Color", "#DE5D83"));
        colorList.add(new ColorModel("Alluring Color", "#C4ABB9"));
        colorList.add(new ColorModel("Pastel Pink Color", "#FFD1DC"));
        colorList.add(new ColorModel("Amaranth Pink Color", "#F19CBB"));
        colorList.add(new ColorModel("Amour Color", "#F5E6EA"));
        colorList.add(new ColorModel("Bubblegum Color", "#FFC1CC"));
        colorList.add(new ColorModel("Azalea Color", "#F7C8DA"));
        colorList.add(new ColorModel("Baby Pink Color", "#F4C2C2"));
        colorList.add(new ColorModel("Baby Pink Color", "#F4C2C2"));
        colorList.add(new ColorModel("Ballerina Color", "#E899BE"));
        colorList.add(new ColorModel("Bambina Color", "#E9D5D3"));
        colorList.add(new ColorModel("Barbie Pink Color", "#E0218A"));
        colorList.add(new ColorModel("Beauty Bush Color", "#EBB9B3"));
        colorList.add(new ColorModel("Birthday Suit Color", "#D4A798"));
        colorList.add(new ColorModel("Blossom Color", "#DCB4BC"));
        colorList.add(new ColorModel("Blush Pink Color", "#FE828C"));
        colorList.add(new ColorModel("Boutique Color", "#DFACB7"));
        colorList.add(new ColorModel("Brandy Rose Color", "#B6857A"));
        colorList.add(new ColorModel("Bridesmaid Color", "#FAE6DF"));
        colorList.add(new ColorModel("Bright Pink Color", "#FE01B1"));
        colorList.add(new ColorModel("Brink Pink Color", "#FB607F"));
        colorList.add(new ColorModel("Coral Color", "#F88379"));
        colorList.add(new ColorModel("Brownish Pink Color", "#C27E79"));
        colorList.add(new ColorModel("Bubble Gum Color", "#FFC1CC"));
        colorList.add(new ColorModel("Hit Pink Color", "#FDA470"));
        colorList.add(new ColorModel("Light Coral Color", "#F08080"));
        colorList.add(new ColorModel("Cameo Pink Color", "#EFBBCC"));
        colorList.add(new ColorModel("Can Color", "#D08A9B"));
        colorList.add(new ColorModel("Candy Pink Color", "#E4717A"));
        colorList.add(new ColorModel("Crepe Color", "#F89883"));
        colorList.add(new ColorModel("Careys Pink Color", "#C99AA0"));
        colorList.add(new ColorModel("Carissma Color", "#E68095"));
        colorList.add(new ColorModel("Carnation Pink Color", "#FF7FA7"));
        colorList.add(new ColorModel("Cerise Pink Color", "#EC3B83"));
        colorList.add(new ColorModel("Chantilly Color", "#EDB8C7"));
        colorList.add(new ColorModel("Charm Color", "#D0748B"));

        colorList.add(new ColorModel("Classic Rose Color", "#F4C8DB"));
        colorList.add(new ColorModel("Congo Pink Color", "#F88379"));
        colorList.add(new ColorModel("Coral Pink Color", "#F88379"));
        colorList.add(new ColorModel("Cornflower Lilac Color", "#FFB0AC"));
        colorList.add(new ColorModel("Barbie Pink Color", "#E0218A"));
        colorList.add(new ColorModel("Cosmos Color", "#FCD5CF"));
        colorList.add(new ColorModel("Mulberry Color", "#C54B8C"));
        colorList.add(new ColorModel("Cupid Color", "#F5B2C5"));
        colorList.add(new ColorModel("Dark Pink Color", "#CB416B"));
        colorList.add(new ColorModel("Lace Color", "#FFD8F0"));
        colorList.add(new ColorModel("Deep Blush Color", "#E36F8A"));
        colorList.add(new ColorModel("Oyster Color", "#F0D8D8"));
        colorList.add(new ColorModel("Dirty Pink Color", "#CA7B80"));
        colorList.add(new ColorModel("Dull Pink Color", "#D5869D"));
        colorList.add(new ColorModel("Dusty Pink Color", "#D58A94"));
        colorList.add(new ColorModel("English Lavender Color", "#B48395"));
        colorList.add(new ColorModel("Faded Pink Color", "#DE9DAC"));
        colorList.add(new ColorModel("Flamingo Pink Color", "#FC8EAC"));
        colorList.add(new ColorModel("Floyd Color", "#DA9CA6"));
        colorList.add(new ColorModel("French Fuchsia Color", "#FD3F92"));
        colorList.add(new ColorModel("Light French Pink Color", "#FD6C9E"));
        colorList.add(new ColorModel("Gray Pink Color", "#C3909B"));
        colorList.add(new ColorModel("French Rose Color", "#F64A8A"));
        colorList.add(new ColorModel("Hopbush Color", "#CD6D93"));
        colorList.add(new ColorModel("Kidman Color", "#CCB7B9"));
        colorList.add(new ColorModel("Puce Color", "#CC8899"));
        colorList.add(new ColorModel("Hot Pink Color", "#FF69B4"));
        colorList.add(new ColorModel("Kobi Color", "#E093AB"));
        colorList.add(new ColorModel("Raspberry Rose Color", "#B3446C"));
        colorList.add(new ColorModel("Lavender Rose Color", "#FBA0E3"));
        colorList.add(new ColorModel("Paradise Pink Color", "#E63E62"));
        colorList.add(new ColorModel("Light Hot Pink Color", "#FFB3DE"));
        colorList.add(new ColorModel("Light Thulian Pink Color", "#E68FAC"));
        colorList.add(new ColorModel("Lullaby Color", "#E2CDD5"));
        colorList.add(new ColorModel("Magenta Pink Color", "#CC338B"));

        colorList.add(new ColorModel("Tulip Pink Color", "#FF8E8E"));
        colorList.add(new ColorModel("Mamma Mia Color", "#D5A4A8"));
        colorList.add(new ColorModel("Mandys Pink Color", "#F2C3B2"));
        colorList.add(new ColorModel("French Pink Color", "#F64A8A"));
        colorList.add(new ColorModel("Marshmallow Color", "#FCDBD2"));
        colorList.add(new ColorModel("Maverick Color", "#C8B1C0"));
        colorList.add(new ColorModel("Mesmerise Color", "#B598A3"));
        colorList.add(new ColorModel("Mountbatten Pink Color", "#997A8D"));
        colorList.add(new ColorModel("Muted Pink Color", "#D1768F"));
        colorList.add(new ColorModel("My Pink Color", "#D68B80"));
        colorList.add(new ColorModel("Nadeshiko Pink Color", "#F6ADC6"));
        colorList.add(new ColorModel("New York Pink Color", "#D7837F"));
        colorList.add(new ColorModel("Old Pink Color", "#C77986"));
        colorList.add(new ColorModel("Old Rose Color", "#C08081"));
        colorList.add(new ColorModel("Orchid Pink Color", "#F2BDCD"));
        colorList.add(new ColorModel("Oriental Pink Color", "#C28E88"));
        colorList.add(new ColorModel("Oyster Pink Color", "#D4B5B0"));
        colorList.add(new ColorModel("Pale Pink Color", "#FADADD"));
        colorList.add(new ColorModel("Pink Lace Color", "#F6CCD7"));
        colorList.add(new ColorModel("Pink Lavender Color", "#D8B2D1"));
        colorList.add(new ColorModel("Pink Light Color", "#FFB6C1"));
        colorList.add(new ColorModel("Pink Salmon Color", "#FF91A4"));
        colorList.add(new ColorModel("Pink Sherbet Color", "#F78FA7"));
        colorList.add(new ColorModel("Pinkish Color", "#D46A7E"));
        colorList.add(new ColorModel("Pinky Color", "#FC86AA"));
        colorList.add(new ColorModel("Powder Pink Color", "#FFB2D0"));
        colorList.add(new ColorModel("Queen Pink Color", "#E8CCD7"));
        colorList.add(new ColorModel("Rosa Color", "#FE86A4"));
        colorList.add(new ColorModel("Rose Color", "#FF007F"));
        colorList.add(new ColorModel("Rose Bonbon Color", "#F9429E"));
        colorList.add(new ColorModel("Rosy Pink Color", "#F6688E"));
        colorList.add(new ColorModel("Ruddy Pink Color", "#E18E96"));
        colorList.add(new ColorModel("Sakura Color", "#E9B7A9"));
        colorList.add(new ColorModel("Schauss Pink Color", "#FF91AF"));
        colorList.add(new ColorModel("Shimmering Blush Color", "#D98695"));
        colorList.add(new ColorModel("Steel Pink Color", "#CC33CC"));
        colorList.add(new ColorModel("Strong Pink Color", "#FF0789"));
        colorList.add(new ColorModel("Super Pink Color", "#CF6BA9"));
        colorList.add(new ColorModel("Sweet Pink Color", "#EE918D"));
        colorList.add(new ColorModel("Mauvelous Color", "#EF98AA"));
        colorList.add(new ColorModel("Brink Color", "#FF6090"));
        colorList.add(new ColorModel("Nude Pink Color", "#DDC0B4"));
        colorList.add(new ColorModel("Tango Pink Color", "#E4717A"));
        colorList.add(new ColorModel("Thulian Pink Color", "#DE6FA1"));
        colorList.add(new ColorModel("Violet Pink Color", "#FB5FFC"));
        colorList.add(new ColorModel("Warm Pink Color", "#FB5581"));
        colorList.add(new ColorModel("Wax Flower Color", "#EEB39E"));
        colorList.add(new ColorModel("Wewak Color", "#F1919A"));
        colorList.add(new ColorModel("Sweet Pink Color", "#EE918D"));
        colorList.add(new ColorModel("Wild Watermelon Color", "#FC6C85"));
        colorList.add(new ColorModel("Zinnwaldite Color", "#EBC2AF"));
// Orange colors
        colorList.add(new ColorModel("Adrenalin Color", "#FF5200"));
        colorList.add(new ColorModel("Orange Color", "#FF8000"));
        colorList.add(new ColorModel("Halloween Orange Color", "#EE5921"));
        colorList.add(new ColorModel("Dark Orange Color", "#FF8C00"));
        colorList.add(new ColorModel("Tangelo Color", "#FC4C02"));
        colorList.add(new ColorModel("Royal Orange Color", "#FF9944"));
        colorList.add(new ColorModel("Pastel Orange Color", "#FEBA4F"));
        colorList.add(new ColorModel("Coral Orange Color", "#FF7F50"));
        colorList.add(new ColorModel("Princeton Orange Color", "#FF8F00"));
        colorList.add(new ColorModel("Alamo Color", "#BA8C66"));
        colorList.add(new ColorModel("Crayola Orange Color", "#FF7538"));
        colorList.add(new ColorModel("Tangerine Color", "#F78702"));
        colorList.add(new ColorModel("Vivid Orange Color", "#FF5E0E"));
        colorList.add(new ColorModel("Cheese Orange Color", "#FFA600"));
        colorList.add(new ColorModel("Alloy Orange Color", "#C46210"));
        colorList.add(new ColorModel("Desert Orange Color", "#ED8E4A"));
        colorList.add(new ColorModel("Amber Color", "#FF7E00"));
        colorList.add(new ColorModel("Flame Color", "#E34A27"));
        colorList.add(new ColorModel("Irish Orange Color", "#F5883F"));
        colorList.add(new ColorModel("Apricot Color", "#E48F67"));
        colorList.add(new ColorModel("Metallic Orange Color", "#E26310"));
        colorList.add(new ColorModel("Ayers Rock Color", "#AE451D"));
        colorList.add(new ColorModel("Goldfish Orange Color", "#FF9913"));
        colorList.add(new ColorModel("Mango Tango Color", "#FB8842"));
        colorList.add(new ColorModel("Willpower Orange Color", "#FD5602"));
        colorList.add(new ColorModel("Bamboo Color", "#BA6F3F"));
        colorList.add(new ColorModel("Lava Orange Color", "#F76806"));
        colorList.add(new ColorModel("Beethoven Color", "#D1946C"));
        colorList.add(new ColorModel("Big Foot Feet Color", "#E88E5A"));
        colorList.add(new ColorModel("Dusty Orange Color", "#E27A53"));
        colorList.add(new ColorModel("Dutch Orange Color", "#FF9B00"));
        colorList.add(new ColorModel("Biscuit Brown Color", "#BB8B67"));
        colorList.add(new ColorModel("Blaze Orange Color", "#FF6600"));
        colorList.add(new ColorModel("Peach Orange Color", "#FFCC99"));
        colorList.add(new ColorModel("Blood Orange Color", "#FE4B03"));
        colorList.add(new ColorModel("Bourbon Color", "#AF6C3E"));



        // Orange colors (continued)
        colorList.add(new ColorModel("Safety Orange Color", "#FF6700"));
        colorList.add(new ColorModel("Brick Orange Color", "#C14A09"));
        colorList.add(new ColorModel("Bright Orange Color", "#FF5B00"));
        colorList.add(new ColorModel("Chocolate Orange Color", "#D2691E"));
        colorList.add(new ColorModel("Brilliant Orange Color", "#E79C51"));
        colorList.add(new ColorModel("Brilliant Scarlet Color", "#E76451"));
        colorList.add(new ColorModel("Salmon Orange Color", "#FF8066"));
        colorList.add(new ColorModel("Brilliant Tangelo Color", "#E78951"));
        colorList.add(new ColorModel("Syracuse Orange Color", "#D44500"));
        colorList.add(new ColorModel("Brilliant Vermilion Color", "#E77751"));
        colorList.add(new ColorModel("Burning Orange Color", "#FF7034"));
        colorList.add(new ColorModel("Burnt Orange Color", "#CC5500"));
        colorList.add(new ColorModel("Burnt Siena Color", "#B75203"));
        colorList.add(new ColorModel("Cadmium Orange Color", "#ED872D"));
        colorList.add(new ColorModel("Tiger Orange Color", "#F96815"));
        colorList.add(new ColorModel("California Color", "#E98C3A"));
        colorList.add(new ColorModel("Greek Orange Color", "#E06E04"));
        colorList.add(new ColorModel("West Side Orange Color", "#FF9916"));
        colorList.add(new ColorModel("Carpe Diem Color", "#E4943D"));
        colorList.add(new ColorModel("Yam Orange Color", "#E17E45"));
        colorList.add(new ColorModel("Carrot Color", "#ED9121"));
        colorList.add(new ColorModel("Cinnabar Color", "#E34234"));
        colorList.add(new ColorModel("Marigold Orange Color", "#EAA221"));
        colorList.add(new ColorModel("Clementine Color", "#E96E00"));
        colorList.add(new ColorModel("Coral Color", "#FF7F00"));
        colorList.add(new ColorModel("Deep Carrot Orange Color", "#E9692C"));
        colorList.add(new ColorModel("Dusty Orange Color", "#F0833A"));
        colorList.add(new ColorModel("Neon Orange Color", "#FFAD00"));
        colorList.add(new ColorModel("Koi Orange Color", "#D15837"));
        colorList.add(new ColorModel("Flush Orange Color", "#FF7F00"));
        colorList.add(new ColorModel("Frenzee Color", "#F7A233"));
        colorList.add(new ColorModel("Rubber Duck Color", "#FFB437"));
        colorList.add(new ColorModel("Salamander Orange Color", "#F05E23"));
        colorList.add(new ColorModel("India Saffron Color", "#FF9933"));
        colorList.add(new ColorModel("Fulvous Color", "#E48400"));
        colorList.add(new ColorModel("Giants Orange Color", "#FE5A1D"));
        colorList.add(new ColorModel("Gold Drop Color", "#F18200"));
        colorList.add(new ColorModel("Spanish Orange Color", "#F06105"));
        colorList.add(new ColorModel("Guggenheim Color", "#FF8E59"));
        colorList.add(new ColorModel("Persimmon Color", "#EC5800"));
        colorList.add(new ColorModel("Heat Wave Color", "#FF7A00"));
        colorList.add(new ColorModel("Terracotta Color", "#E2725B"));
        colorList.add(new ColorModel("Juicy Color", "#FF8B00"));
        colorList.add(new ColorModel("Mandarin Color", "#F37A48"));
        colorList.add(new ColorModel("Orange Peel Color", "#FF9F00"));
        colorList.add(new ColorModel("Peach Orange Color", "#FFCC99"));
        colorList.add(new ColorModel("Vivid Tangelo Color", "#EC7625"));
        colorList.add(new ColorModel("Pizazz Color", "#FF9000"));
        colorList.add(new ColorModel("Buff Orange Color", "#F2CA85"));


        // Yellow colors (continued)
        colorList.add(new ColorModel("Pomegranate Color", "#F34723"));
        colorList.add(new ColorModel("Pumpkin Color", "#F5761A"));
        colorList.add(new ColorModel("Mango Color", "#FFA62B"));
        colorList.add(new ColorModel("Bronze Orange Color", "#CD7F32"));
        colorList.add(new ColorModel("Aureoline Color", "#FFA824"));

// Yellow color names
        colorList.add(new ColorModel("Bumblebee Color", "#FCE205"));
        colorList.add(new ColorModel("School Bus Color", "#FFD800"));
        colorList.add(new ColorModel("Beige Color", "#F5F5DC"));
        colorList.add(new ColorModel("Sunshine Yellow Color", "#FFFD37"));
        colorList.add(new ColorModel("Macaroon Color", "#F9E076"));
        colorList.add(new ColorModel("Honey Color", "#FFC30B"));
        colorList.add(new ColorModel("Canary Yellow Color", "#FFEF00"));
        colorList.add(new ColorModel("Spanish Yellow Color", "#F9D73D"));
        colorList.add(new ColorModel("Golden Tainoi Color", "#FFC152"));
        colorList.add(new ColorModel("Banana Color", "#FFE135"));
        colorList.add(new ColorModel("Light Khaki Color", "#F0E68C"));
        colorList.add(new ColorModel("Tuscany Color", "#FCD12A"));
        colorList.add(new ColorModel("Yellow – Pantone Color", "#FEDF00"));
        colorList.add(new ColorModel("Banana Color", "#FAFE4B"));
        colorList.add(new ColorModel("Vivid Yellow Color", "#FFE302"));
        colorList.add(new ColorModel("Light Brilliant Amber Color", "#FFD865"));
        colorList.add(new ColorModel("Amber Color", "#FFBF00"));
        colorList.add(new ColorModel("Bright Yellow Color", "#FFFD01"));
        colorList.add(new ColorModel("Baby Yellow Color", "#FCEF91"));
        colorList.add(new ColorModel("Gold Color", "#FFD700"));
        colorList.add(new ColorModel("Butter Color", "#FFFD74"));
        colorList.add(new ColorModel("Golden Poppy Color", "#FCC200"));
        colorList.add(new ColorModel("Sunflower Color", "#FFDA03"));
        colorList.add(new ColorModel("Buzz Color", "#FBEB50"));
        colorList.add(new ColorModel("Vibrant Yellow Color", "#FFDA29"));
        colorList.add(new ColorModel("Cadmium Lemon Color", "#FFE303"));
        colorList.add(new ColorModel("Mustard Color", "#FEDC56"));
        colorList.add(new ColorModel("Relax Yellow Color", "#F3E496"));
        colorList.add(new ColorModel("Snapchat Yellow Color", "#FFFC00"));
        colorList.add(new ColorModel("Royal Yellow Color", "#FADA5E"));
        colorList.add(new ColorModel("Butter Color", "#FFFD74"));
        colorList.add(new ColorModel("Fire Yellow Color", "#FEDE17"));
        colorList.add(new ColorModel("Cream Color", "#FFFFCC"));
        colorList.add(new ColorModel("Rainbow Yellow Color", "#F5DE10"));
        colorList.add(new ColorModel("Golden Rod Color", "#F9BC08"));
        colorList.add(new ColorModel("Cadmium Color", "#FFF600"));
        colorList.add(new ColorModel("Cyber Color", "#FFD300"));
        colorList.add(new ColorModel("Saffron Color", "#F4C430"));
        colorList.add(new ColorModel("Ochre Yellow Color", "#B5904B"));
        colorList.add(new ColorModel("Canary Yellow Color", "#FFEF00"));
        colorList.add(new ColorModel("Candy Corn Color", "#FBEC5D"));
        colorList.add(new ColorModel("Gargoyle Gas Color", "#FFDF46"));
        colorList.add(new ColorModel("Pastel Yellow Color", "#FFFE71"));
        colorList.add(new ColorModel("Aureolin Color", "#FDEE00"));
        colorList.add(new ColorModel("Hot Yellow Color", "#FFDA00"));
        colorList.add(new ColorModel("Custard Color", "#FFFD78"));
        colorList.add(new ColorModel("Sand Yellow Color", "#FCE166"));
        colorList.add(new ColorModel("Daffodil Color", "#FFFF31"));
        colorList.add(new ColorModel("Golden Poppy Color", "#FCC200"));
        colorList.add(new ColorModel("Golden Sand Color", "#EACE6A"));
        colorList.add(new ColorModel("Munsell Yellow Color", "#EFCC00"));
        colorList.add(new ColorModel("Golden Yellow Color", "#FFDF00"));
        colorList.add(new ColorModel("Corn Color", "#FBEC5D"));
        colorList.add(new ColorModel("Mikado Color", "#FFC40C"));
        colorList.add(new ColorModel("Gorse Color", "#FDE336"));
        colorList.add(new ColorModel("Hansa Yellow Color", "#E9D66B"));
        colorList.add(new ColorModel("Hathaway Color", "#F7DE94"));
        colorList.add(new ColorModel("Holiday Color", "#F5EB4F"));
        colorList.add(new ColorModel("Icterine Color", "#FCF75E"));
        colorList.add(new ColorModel("Jasmine Color", "#F8DE7E"));
        colorList.add(new ColorModel("Manz Color", "#E4DB55"));
        colorList.add(new ColorModel("Citrine Color", "#E4D00A"));
        colorList.add(new ColorModel("Banana Mania Color", "#FAE7B5"));
        colorList.add(new ColorModel("Dijon Color", "#C49102"));
        colorList.add(new ColorModel("Marigold Yellow Color", "#FBE870"));
        colorList.add(new ColorModel("Selective Yellow Color", "#FFBA00"));
        colorList.add(new ColorModel("Empire Color", "#F7D000"));
        colorList.add(new ColorModel("Lemon Chiffon Color", "#FFFACD"));
        colorList.add(new ColorModel("Vintage Yellow Color", "#CBA92B"));
        colorList.add(new ColorModel("Neon Yellow Color", "#CFFF04"));

// Green colors
        colorList.add(new ColorModel("Green Color", "#008000"));
        colorList.add(new ColorModel("Forest Color", "#0B6623"));
        colorList.add(new ColorModel("Emerald Color", "#50C878"));
        colorList.add(new ColorModel("Pine Color", "#01796F"));
        colorList.add(new ColorModel("Jungle Color", "#29AB87"));
        colorList.add(new ColorModel("Hunter Color", "#3F704D"));
        colorList.add(new ColorModel("Mint Color", "#98FB98"));
        colorList.add(new ColorModel("Green (Munsell) Color", "#00A877"));
        colorList.add(new ColorModel("Olive Color", "#708238"));
        colorList.add(new ColorModel("Jade Color", "#00A86B"));
        colorList.add(new ColorModel("Pine Color", "#01796F"));
        colorList.add(new ColorModel("Bluish Green Color", "#10A674"));
        colorList.add(new ColorModel("Phthalo Green Color", "#123524"));
// Green colors (continued)
        colorList.add(new ColorModel("Jewel Color", "#126B40"));
        colorList.add(new ColorModel("Algae Color", "#54AC68"));
        colorList.add(new ColorModel("Malachite Color", "#0BDA51"));
        colorList.add(new ColorModel("Pistachio Color", "#93C572"));
        colorList.add(new ColorModel("Mantis Color", "#74C365"));
        colorList.add(new ColorModel("Algae Color", "#21C36F"));
        colorList.add(new ColorModel("Christmas Green Color", "#00873E"));
        colorList.add(new ColorModel("Amazon Color", "#387B54"));
        colorList.add(new ColorModel("Lime Color", "#00FF00"));
        colorList.add(new ColorModel("Android Color", "#A4C639"));
        colorList.add(new ColorModel("Lucky Break Color", "#3E762D"));
        colorList.add(new ColorModel("Ao Color", "#008000"));
        colorList.add(new ColorModel("Jungle Juice Color", "#2F7532"));
        colorList.add(new ColorModel("Chartreuse Color", "#7FFF00"));
        colorList.add(new ColorModel("Anise Color", "#A7D67D"));
        colorList.add(new ColorModel("Office Green Color", "#008000"));
        colorList.add(new ColorModel("Artichoke – Pantone Color", "#4B6F44"));
        colorList.add(new ColorModel("Apple Color", "#4FA83D"));
        colorList.add(new ColorModel("Ocean Green Color", "#3D9973"));
        colorList.add(new ColorModel("Army Green Color", "#4B5320"));
        colorList.add(new ColorModel("Parsley Color", "#134F19"));
        colorList.add(new ColorModel("Artichoke Color", "#8F9779"));
        colorList.add(new ColorModel("Irish Color", "#009A44"));
        colorList.add(new ColorModel("Neon Green Color", "#39FF14"));
        colorList.add(new ColorModel("Persian Color", "#00A693"));
        colorList.add(new ColorModel("Asparagus Color", "#77AB56"));
        colorList.add(new ColorModel("Polished Pine Color", "#5DA493"));
        colorList.add(new ColorModel("Robin Hood Color", "#167057"));
        colorList.add(new ColorModel("Sea Green Color", "#2E8B57"));
        colorList.add(new ColorModel("John Deere Green Color", "#367C2B"));
        colorList.add(new ColorModel("Viridian Color", "#609078"));
        colorList.add(new ColorModel("Atlantis Color", "#97CD2D"));
        colorList.add(new ColorModel("Sacramento Color", "#00563F"));
        colorList.add(new ColorModel("Hunter Color", "#355E3B"));
        colorList.add(new ColorModel("Avocado Color", "#568203"));
        colorList.add(new ColorModel("Shamrock Color", "#009E60"));
        colorList.add(new ColorModel("Baby Green Color", "#8CFF9E"));
        colorList.add(new ColorModel("Bay Leaf Color", "#7BB18D"));
        colorList.add(new ColorModel("Sage Color", "#88B378"));
        colorList.add(new ColorModel("San Felix Color", "#0B6207"));
        colorList.add(new ColorModel("Bilbao Color", "#327C14"));
        colorList.add(new ColorModel("Bitter Lemon Color", "#CAE00D"));
        colorList.add(new ColorModel("Bluish Green Color", "#10A674"));
        colorList.add(new ColorModel("Booger Color", "#9BB53C"));
        colorList.add(new ColorModel("Bottle Green Color", "#006A4E"));

        // Blue colors (continued)
        colorList.add(new ColorModel("Breaker Bay Color", "#517B78"));
        colorList.add(new ColorModel("Bright Green Color", "#01FF07"));
        colorList.add(new ColorModel("Verdun Color", "#487800"));
        colorList.add(new ColorModel("Brilliant Emerald Color", "#51E764"));
        colorList.add(new ColorModel("British Racing Color", "#004225"));
        colorList.add(new ColorModel("Brunswick Color", "#1B4D3E"));
        colorList.add(new ColorModel("Kelly Green Color", "#4CBB17"));
        colorList.add(new ColorModel("French Lime Color", "#9EFD38"));
        colorList.add(new ColorModel("Cactus Color", "#587156"));
        colorList.add(new ColorModel("Cadmium Color", "#006B3C"));
        colorList.add(new ColorModel("Cal Poly Color", "#1E4D2B"));
        colorList.add(new ColorModel("Camarone Color", "#00581A"));
        colorList.add(new ColorModel("Cardin Color", "#01361C"));
        colorList.add(new ColorModel("Castleton Color", "#00563B"));
        colorList.add(new ColorModel("Pear Color", "#D1E231"));
        colorList.add(new ColorModel("Chlorophyll Color", "#4AFF00"));
        colorList.add(new ColorModel("Celadon Color", "#ACE1AF"));
        colorList.add(new ColorModel("Chateau Color", "#40A860"));
        colorList.add(new ColorModel("Cinnabar Color", "#61B329"));
        colorList.add(new ColorModel("Cobalt Green Color", "#3D9140"));
        colorList.add(new ColorModel("Corn Green Color", "#71A92C"));
        colorList.add(new ColorModel("Paolo Veronese Color", "#009B7D"));
        colorList.add(new ColorModel("Citrus Color", "#9FB70A"));
        colorList.add(new ColorModel("Como Color", "#4C785C"));
        colorList.add(new ColorModel("Cool Green Color", "#33B864"));
        colorList.add(new ColorModel("Turquoise Green Color", "#A0D6B4"));
        colorList.add(new ColorModel("Crusoe Color", "#004816"));
        colorList.add(new ColorModel("Dark Emerald Color", "#27592D"));
        colorList.add(new ColorModel("Dark Fern Color", "#0A480D"));
        colorList.add(new ColorModel("Dark Forest Green Color", "#002D04"));
        colorList.add(new ColorModel("Dark Green Color", "#006400"));
        colorList.add(new ColorModel("Dark Mint Color", "#48C072"));
        colorList.add(new ColorModel("Spring Color", "#00F0A8"));
        colorList.add(new ColorModel("Dark Spring Color", "#177245"));
        colorList.add(new ColorModel("Dartmouth Color", "#00693E"));
        colorList.add(new ColorModel("Deep Spring Color", "#00592D"));
        colorList.add(new ColorModel("Dollar Bill Color", "#85BB65"));
        colorList.add(new ColorModel("Dusty Green Color", "#76A973"));
        colorList.add(new ColorModel("Foam Green Color", "#90FDA9"));
        colorList.add(new ColorModel("Freedom Color", "#006246"));
        colorList.add(new ColorModel("Old Moss Green Color", "#867E36"));
        colorList.add(new ColorModel("Fringy Flower Color", "#B1E2C1"));
        colorList.add(new ColorModel("Fruit Salad Color", "#4BA351"));
        colorList.add(new ColorModel("Go Green Color", "#00AB66"));
        colorList.add(new ColorModel("Gossamer Color", "#069B81"));
        colorList.add(new ColorModel("Gossip Color", "#9FD385"));
        colorList.add(new ColorModel("Green Gray Color", "#77926F"));
        colorList.add(new ColorModel("Green Haze Color", "#01A368"));
        colorList.add(new ColorModel("Green Pea Color", "#1D6142"));
        colorList.add(new ColorModel("Caribbean Color", "#00CC99"));
        colorList.add(new ColorModel("Greenish Color", "#40A368"));
        colorList.add(new ColorModel("Jeepers Creepers Color", "#29A98B"));
        colorList.add(new ColorModel("Observatory Color", "#008F70"));
        colorList.add(new ColorModel("Keppel Color", "#3AB09E"));
        colorList.add(new ColorModel("Gum Leaf Color", "#ACC9B2"));
        colorList.add(new ColorModel("Illuminating Emerald Color", "#319177"));
        colorList.add(new ColorModel("Dark Aquamarine Color", "#017371"));
        colorList.add(new ColorModel("Seafoam Color", "#80F9AD"));
        colorList.add(new ColorModel("Genoa Color", "#15736B"));
        colorList.add(new ColorModel("Teal Color", "#008080"));
        colorList.add(new ColorModel("Caesar Color", "#1B6767"));
        colorList.add(new ColorModel("Deep Sea Color", "#01826B"));
        colorList.add(new ColorModel("Dull Teal Color", "#5F9E8F"));
        colorList.add(new ColorModel("Dusty Teal Color", "#4C9085"));
        colorList.add(new ColorModel("Niagara Color", "#06A189"));


        colorList.add(new ColorModel("Ice Blue color", "#99FFFF"));
        colorList.add(new ColorModel("Turquoise Blue color", "#00FFEF"));
        colorList.add(new ColorModel("Fluorescent color", "#15F4EE"));
        colorList.add(new ColorModel("Bright Turquoise color", "#08E8DE"));
        colorList.add(new ColorModel("Light Turquoise color", "#AFEEEE"));
        colorList.add(new ColorModel("Blue Light color", "#ADD8E6"));
        colorList.add(new ColorModel("Seafoam Blue color", "#78D1B6"));
        colorList.add(new ColorModel("Sky Blue color", "#ADD8E6"));
        colorList.add(new ColorModel("Ocean Blue color", "#009DC4"));
        colorList.add(new ColorModel("Alaskan color", "#6DA9D2"));
        colorList.add(new ColorModel("Sky Blue Light color", "#87CEFA"));
        colorList.add(new ColorModel("Slate color", "#007FFF"));
        colorList.add(new ColorModel("Snap color", "#5BA0D0"));
        colorList.add(new ColorModel("Star Command color", "#007BB8"));
        colorList.add(new ColorModel("Steel Blue Light color", "#B0C4DE"));
        colorList.add(new ColorModel("Teal Blue color", "#01889F"));
        colorList.add(new ColorModel("Azure color", "#007FFF"));
        colorList.add(new ColorModel("Jordy color", "#7AAAE0"));
        colorList.add(new ColorModel("Bleu De France color", "#318CE7"));
        colorList.add(new ColorModel("Imperial color", "#002395"));
        colorList.add(new ColorModel("Ultramarine color", "#120A8F"));
        colorList.add(new ColorModel("Brewers color", "#0A2351"));
        colorList.add(new ColorModel("Peacock color", "#33A1C9"));
        colorList.add(new ColorModel("Absolute Zero color", "#0048BA"));
        colorList.add(new ColorModel("Fresh Air color", "#A6E7FF"));
        colorList.add(new ColorModel("Celadon color", "#007BA7"));
        colorList.add(new ColorModel("Stone color", "#819EA8"));
        colorList.add(new ColorModel("Spruce color", "#617178"));
        colorList.add(new ColorModel("Byzantine color", "#3457D5"));
        colorList.add(new ColorModel("Cornflower color", "#6495ED"));
        colorList.add(new ColorModel("Crayola Blue color", "#1F75FE"));
        colorList.add(new ColorModel("Celeste color", "#B2FFFF"));
        colorList.add(new ColorModel("Greenish Blue color", "#0B8B87"));
        colorList.add(new ColorModel("Frozen color", "#9DB6C6"));
        colorList.add(new ColorModel("Aero color", "#7CB9E8"));
        colorList.add(new ColorModel("Marine color", "#042E60"));
        colorList.add(new ColorModel("Capri color", "#00BFFF"));
        colorList.add(new ColorModel("Catalina color", "#062A78"));
        colorList.add(new ColorModel("Fountain color", "#56B4BE"));
        colorList.add(new ColorModel("Galactica color", "#303655"));
        colorList.add(new ColorModel("Air Force color", "#00308F"));
        colorList.add(new ColorModel("Blue Ribbon color", "#0066FF"));
        colorList.add(new ColorModel("Blue Gray color", "#6699CC"));
        colorList.add(new ColorModel("Allports color", "#0076A3"));
        colorList.add(new ColorModel("Anakiwa color", "#8CCEEA"));
        colorList.add(new ColorModel("Blueberry color", "#464196"));
        colorList.add(new ColorModel("Danube color", "#5B89C0"));
        colorList.add(new ColorModel("Bright Blue color", "#0165FC"));
        colorList.add(new ColorModel("Indigo Blue color", "#3F00FF"));
        colorList.add(new ColorModel("Trypan color", "#1C05B3"));
        colorList.add(new ColorModel("Picotee color", "#2E2787"));
        colorList.add(new ColorModel("Chelsea color", "#034694"));
        colorList.add(new ColorModel("Blue Jeans color", "#4E6590"));
        colorList.add(new ColorModel("Aquamarine Blue color", "#71D9E2"));
        colorList.add(new ColorModel("Aquarius color", "#43A8C5"));
        colorList.add(new ColorModel("Bluish color", "#2976BB"));
        colorList.add(new ColorModel("Cerulean Frost color", "#6D9BC3"));
        colorList.add(new ColorModel("Charlotte color", "#A4DCE6"));
        colorList.add(new ColorModel("Peacock color", "#005F69"));
        colorList.add(new ColorModel("Chathams color", "#175579"));
        colorList.add(new ColorModel("Dusk Blue color", "#26538D"));
        colorList.add(new ColorModel("Malibu color", "#66B7E1"));
        colorList.add(new ColorModel("Clear Blue color", "#247AFD"));
        colorList.add(new ColorModel("Cool Blue color", "#4984B8"));
        colorList.add(new ColorModel("Aqua color", "#0AFFFF"));
        colorList.add(new ColorModel("Robin Egg color", "#00CCCC"));
        colorList.add(new ColorModel("Bright Cerulean color", "#1DACD6"));
        colorList.add(new ColorModel("Arapawa color", "#110C6C"));
        colorList.add(new ColorModel("Ball color", "#21ABCD"));
        colorList.add(new ColorModel("Believe color", "#352F77"));
        colorList.add(new ColorModel("Phthalo Blue color", "#000F89"));
        colorList.add(new ColorModel("Oxford color", "#002147"));
        colorList.add(new ColorModel("Biscay color", "#1B3162"));
        colorList.add(new ColorModel("Bright Navy color", "#1974D2"));
        colorList.add(new ColorModel("Bright Sky color", "#02CCFE"));
        colorList.add(new ColorModel("Comfort Zone color", "#A2B9D2"));
        colorList.add(new ColorModel("Arctic color", "#C6E6FB"));
        colorList.add(new ColorModel("Lure color", "#2F77A9"));
        colorList.add(new ColorModel("Polynesian color", "#224C98"));
        colorList.add(new ColorModel("Congress Blue color", "#02478E"));
        colorList.add(new ColorModel("Cyan Azure color", "#4E82B4"));
        colorList.add(new ColorModel("Cyan Blue color", "#00FFFF"));
        colorList.add(new ColorModel("Cyan Blue Azure color", "#4682BF"));
        colorList.add(new ColorModel("Bayern color", "#0066B2"));
        colorList.add(new ColorModel("Pantone Blue color", "#0018A8"));
        colorList.add(new ColorModel("Dark Blue color", "#00008B"));
        colorList.add(new ColorModel("Dark Midnight color", "#003366"));
        colorList.add(new ColorModel("Dark Pastel Blue color", "#779ECB"));
        colorList.add(new ColorModel("Deep Sky color", "#00688B"));
        colorList.add(new ColorModel("Slate color", "#6A5ACD"));
        colorList.add(new ColorModel("Savoy color", "#4B61D1"));
        colorList.add(new ColorModel("Duke color", "#00009C"));
        colorList.add(new ColorModel("Dull Blue color", "#49759C"));
        colorList.add(new ColorModel("Light Cerulean color", "#8BD0E7"));
        colorList.add(new ColorModel("Limitless color", "#254B75"));
        colorList.add(new ColorModel("Ford color", "#2C3968"));
        colorList.add(new ColorModel("IBM color", "#0530AD"));
        colorList.add(new ColorModel("Twitter color", "#1DA1F2"));
        colorList.add(new ColorModel("Dell color", "#0076CE"));
        colorList.add(new ColorModel("Little Boy color", "#6CA0DC"));

        colorList.add(new ColorModel("Imperial Purple color", "#602F6B"));
        colorList.add(new ColorModel("Plum color", "#673147"));
        colorList.add(new ColorModel("Mauve color", "#E0B0FF"));
        colorList.add(new ColorModel("Tyrian color", "#66023C"));
        colorList.add(new ColorModel("Mulberry color", "#C54B8C"));
        colorList.add(new ColorModel("Periwinkle color", "#BE93E4"));
        colorList.add(new ColorModel("Orchid color", "#DA70D6"));
        colorList.add(new ColorModel("Purple Heart color", "#7442C8"));
        colorList.add(new ColorModel("Affair color", "#714693"));
        colorList.add(new ColorModel("Byzantine color", "#BD33A4"));
        colorList.add(new ColorModel("Purpureus color", "#9A4EAE"));
        colorList.add(new ColorModel("Boogie Wonderland color", "#84579B"));
        colorList.add(new ColorModel("Bright Lavender color", "#BF94E4"));
        colorList.add(new ColorModel("Bruise color", "#7E4071"));
        colorList.add(new ColorModel("Palatinate color", "#72246C"));
        colorList.add(new ColorModel("French Mauve color", "#D473D4"));
        colorList.add(new ColorModel("Lavender Blush color", "#FFF0F5"));
        colorList.add(new ColorModel("Thistle color", "#D8BFD8"));
        colorList.add(new ColorModel("Mountbatten color", "#997A8D"));
        colorList.add(new ColorModel("Ooh La color", "#A088A6"));
        colorList.add(new ColorModel("English Violet color", "#563C5C"));
        colorList.add(new ColorModel("Abracadabra color", "#564985"));
        colorList.add(new ColorModel("Fuchsia color", "#FF00FF"));
        colorList.add(new ColorModel("Jam color", "#67032F"));
        colorList.add(new ColorModel("Amaranth Purple color", "#AB274F"));
        colorList.add(new ColorModel("Phlox color", "#DF00FF"));
        colorList.add(new ColorModel("Iris color", "#9867C5"));
        colorList.add(new ColorModel("Cardinal color", "#8A244E"));
        colorList.add(new ColorModel("Carnival color", "#7E2A65"));
        colorList.add(new ColorModel("Ce Soir color", "#9271A7"));
        colorList.add(new ColorModel("Pale Purple color", "#AA98A9"));
        colorList.add(new ColorModel("French Lilac color", "#86608E"));
        colorList.add(new ColorModel("Eggplant color", "#483248"));
        colorList.add(new ColorModel("Indigo color", "#4B0082"));
        colorList.add(new ColorModel("Veronica color", "#A020F0"));
        colorList.add(new ColorModel("Centre Stage color", "#833174"));
        colorList.add(new ColorModel("Long Distance color", "#6F456E"));
        colorList.add(new ColorModel("Centaurian color", "#6E5977"));
        colorList.add(new ColorModel("Bubblegum color", "#8378C7"));
        colorList.add(new ColorModel("Chapta And Verse color", "#574C5E"));
        colorList.add(new ColorModel("Lipstick Stain color", "#8E4785"));
        colorList.add(new ColorModel("Bright Lilac color", "#C95EFB"));

        colorList.add(new ColorModel("Bright Purple color", "#BE03FD"));
        colorList.add(new ColorModel("Amethyst color", "#9966CC"));
        colorList.add(new ColorModel("Fog color", "#D5C7E8"));
        colorList.add(new ColorModel("Barney color", "#AC1DB8"));
        colorList.add(new ColorModel("Dull Purple color", "#84597E"));
        colorList.add(new ColorModel("Smyrna color", "#A2627A"));
        colorList.add(new ColorModel("Dusky Purple color", "#895B7B"));
        colorList.add(new ColorModel("Dusty Lavender color", "#AC86A8"));
        colorList.add(new ColorModel("Little Princess color", "#E9DCE5"));
        colorList.add(new ColorModel("Faded Purple color", "#795F80"));
        colorList.add(new ColorModel("East Side color", "#AA8CBC"));
        colorList.add(new ColorModel("Clairvoyant color", "#480656"));
        colorList.add(new ColorModel("Autumn Purple color", "#834468"));
        colorList.add(new ColorModel("Baby Purple color", "#CA9BF7"));
        colorList.add(new ColorModel("Purplish Orchid color", "#8B4789"));
        colorList.add(new ColorModel("African Violet color", "#B284BE"));
        colorList.add(new ColorModel("Cold Purple color", "#9D8ABF"));
        colorList.add(new ColorModel("Dreamweaver color", "#DCD5DE"));
        colorList.add(new ColorModel("Black Currant color", "#540E32"));
        colorList.add(new ColorModel("Dark Lavender color", "#734F96"));
        colorList.add(new ColorModel("Dark Lilac color", "#9C6DA5"));
        colorList.add(new ColorModel("Fun Fair color", "#772C68"));
        colorList.add(new ColorModel("Deep Mauve color", "#D473D4"));
        colorList.add(new ColorModel("Pastel Purple color", "#B39EB5"));
        colorList.add(new ColorModel("Biloba Flower color", "#AE99D2"));
        colorList.add(new ColorModel("Blurple color", "#5539CC"));
        colorList.add(new ColorModel("Berry – Crayola color", "#843179"));
        colorList.add(new ColorModel("Glossy Grape color", "#AB92B3"));
        colorList.add(new ColorModel("Heather color", "#A484AC"));
        colorList.add(new ColorModel("Plum Web color", "#D793D4"));
        colorList.add(new ColorModel("Hot Purple color", "#CB00F5"));
        colorList.add(new ColorModel("Royal Purple color", "#4B006E"));
        colorList.add(new ColorModel("Funtasia color", "#4C3371"));
        colorList.add(new ColorModel("Traditional Purple color", "#8E4585"));
        colorList.add(new ColorModel("Genie color", "#833E77"));
        colorList.add(new ColorModel("Purplish color", "#94568C"));
        colorList.add(new ColorModel("Old Lavender color", "#796878"));
        colorList.add(new ColorModel("Languid Lavender color", "#D6CADD"));
        colorList.add(new ColorModel("Wisteria color", "#BCA7E8"));
        colorList.add(new ColorModel("Lavender color", "#9F90D0"));
        colorList.add(new ColorModel("Magnolia color", "#F8F4FF"));
        colorList.add(new ColorModel("Lavender Blue color", "#8B88F8"));
        colorList.add(new ColorModel("Lavender Gray color", "#BDBBD7"));
        colorList.add(new ColorModel("Razzmic Berry color", "#8D4E85"));
        colorList.add(new ColorModel("Mauveine color", "#8D029B"));
        colorList.add(new ColorModel("Lightish Purple color", "#A552E6"));
        colorList.add(new ColorModel("Lilac color", "#C8A2C8"));
        colorList.add(new ColorModel("Carolina Plum color", "#9B84A1"));
        colorList.add(new ColorModel("Lilac Bush color", "#9470C4"));
        colorList.add(new ColorModel("Lily color", "#C19FB3"));
        colorList.add(new ColorModel("London Hue color", "#AE94AB"));
        colorList.add(new ColorModel("Long Shot color", "#8776B6"));
        colorList.add(new ColorModel("Kalamata color", "#705160"));
        colorList.add(new ColorModel("Lilac Luster color", "#AE98AA"));
        colorList.add(new ColorModel("Lavender color", "#E6E6FA"));
        colorList.add(new ColorModel("Lavender Purple color", "#967BB6"));
        colorList.add(new ColorModel("Lenurple color", "#BA93D8"));
        colorList.add(new ColorModel("Light Blue Violet color", "#AE8BE7"));
        colorList.add(new ColorModel("Violet color", "#8F00FF"));
        colorList.add(new ColorModel("Rhythm color", "#777696"));
        colorList.add(new ColorModel("Pale Lavender color", "#DCD0FF"));
        colorList.add(new ColorModel("Pastel Violet color", "#CB99C9"));
        colorList.add(new ColorModel("Pomp And Power color", "#86608E"));
        colorList.add(new ColorModel("Regalia color", "#522D80"));


        colorList.add(new ColorModel("Brown color", "#653700"));
        colorList.add(new ColorModel("Burnt Umber color", "#8A3324"));
        colorList.add(new ColorModel("Russet color", "#80461B"));
        colorList.add(new ColorModel("Auburn color", "#A52A2A"));
        colorList.add(new ColorModel("Bronze color", "#CD7F32"));
        colorList.add(new ColorModel("Tan color", "#D2B48C"));
        colorList.add(new ColorModel("Brown Ochre color", "#87421F"));
        colorList.add(new ColorModel("Copper color", "#B87333"));
        colorList.add(new ColorModel("Cigar color", "#773F1A"));
        colorList.add(new ColorModel("Chocolate color", "#7B3F00"));
        colorList.add(new ColorModel("Cinnamon color", "#7B3F00"));
        colorList.add(new ColorModel("Burnt Maroon color", "#420303"));
        colorList.add(new ColorModel("Ochre color", "#CC7722"));
        colorList.add(new ColorModel("Taupe color", "#483C32"));
        colorList.add(new ColorModel("Cocoa color", "#875F42"));
        colorList.add(new ColorModel("Light Brown color", "#B5651D"));
        colorList.add(new ColorModel("Cajun color", "#662F2B"));
        colorList.add(new ColorModel("Magma color", "#875639"));
        colorList.add(new ColorModel("Hawaiian Tan color", "#99522B"));
        colorList.add(new ColorModel("Bean color", "#3D0C02"));
        colorList.add(new ColorModel("Saddle color", "#8B4513"));
        colorList.add(new ColorModel("Hazard color", "#A3532A"));
        colorList.add(new ColorModel("Heartwood color", "#A6602F"));
        colorList.add(new ColorModel("Chocolate Brown color", "#411900"));
        colorList.add(new ColorModel("Sienna color", "#A0522D"));
        colorList.add(new ColorModel("Cape Palliser color", "#75482F"));
        colorList.add(new ColorModel("Antique Brass color", "#CD9575"));
        colorList.add(new ColorModel("Grizzly color", "#885818"));
        colorList.add(new ColorModel("Brownie color", "#964B00"));
        colorList.add(new ColorModel("Hairy Heath color", "#633528"));
        colorList.add(new ColorModel("Mai Tai color", "#A56531"));
        colorList.add(new ColorModel("Burnt Sienna color", "#683332"));
        colorList.add(new ColorModel("Ginger color", "#B06500"));
        colorList.add(new ColorModel("Cedar color", "#3E1C14"));
        colorList.add(new ColorModel("Sepia color", "#704214"));
        colorList.add(new ColorModel("Scoria color", "#532620"));
        colorList.add(new ColorModel("Tan color", "#8B5A2B"));
        colorList.add(new ColorModel("Fawn color", "#E5AA70"));
        colorList.add(new ColorModel("Heatwave color", "#6E2620"));
        colorList.add(new ColorModel("Clay color", "#B66A50"));
        colorList.add(new ColorModel("Rust color", "#B7410E"));
        colorList.add(new ColorModel("Meteor color", "#BB7431"));
        colorList.add(new ColorModel("Charisma color", "#854926"));
        colorList.add(new ColorModel("Buff color", "#B38C58"));
        colorList.add(new ColorModel("Lone Ranger color", "#87614F"));
        colorList.add(new ColorModel("Buffalo color", "#765F57"));
        colorList.add(new ColorModel("Bull Shot color", "#75442B"));
        colorList.add(new ColorModel("Bullion color", "#956A3E"));
        colorList.add(new ColorModel("Mexican Wave color", "#B64A32"));
        colorList.add(new ColorModel("Claypot color", "#AB6950"));
        colorList.add(new ColorModel("Bole color", "#79443B"));
        colorList.add(new ColorModel("Bungy color", "#AC713C"));
        colorList.add(new ColorModel("Coffee color", "#6F4E37"));
        colorList.add(new ColorModel("Burnished Orange color", "#92543A"));
        colorList.add(new ColorModel("Hot Chocolate color", "#3D2622"));
        colorList.add(new ColorModel("Mustang color", "#7F352E"));
        colorList.add(new ColorModel("Chelsea Gem color", "#95532F"));
        colorList.add(new ColorModel("Cinnamon color", "#D2691E"));

        colorList.add(new ColorModel("Buttered Rum color", "#9D702E"));
        colorList.add(new ColorModel("Brown Rust color", "#AF593E"));
        colorList.add(new ColorModel("Brown Sugar color", "#8E6540"));
        colorList.add(new ColorModel("Brownie Points color", "#6E4233"));
        colorList.add(new ColorModel("Piper color", "#9D5432"));
        colorList.add(new ColorModel("Kakaramea color", "#6E2C25"));
        colorList.add(new ColorModel("Hukanui color", "#572A23"));
        colorList.add(new ColorModel("Brownish color", "#9C6D57"));
        colorList.add(new ColorModel("Rust Brown color", "#8B3103"));
        colorList.add(new ColorModel("Brownish Gray color", "#86775F"));
        colorList.add(new ColorModel("Auburn color", "#9A3001"));
        colorList.add(new ColorModel("Ash Brown color", "#98623C"));
        colorList.add(new ColorModel("Adobe color", "#BD6C48"));
        colorList.add(new ColorModel("Jalapeno color", "#701C28"));
        colorList.add(new ColorModel("Golden Brown color", "#996515"));
        colorList.add(new ColorModel("Acorn color", "#D7A98C"));
        colorList.add(new ColorModel("Afficionado color", "#453638"));
        colorList.add(new ColorModel("Alter Ego color", "#AB4C48"));
        colorList.add(new ColorModel("Jarrah Stain color", "#57332C"));
        colorList.add(new ColorModel("Axis color", "#846C55"));
        colorList.add(new ColorModel("Brown Nose color", "#6B4423"));
        colorList.add(new ColorModel("Footloose color", "#A4613A"));
        colorList.add(new ColorModel("Jazz color", "#5F2C2F"));
        colorList.add(new ColorModel("Mahogany color", "#C04000"));
        colorList.add(new ColorModel("French Puce color", "#4E1609"));
        colorList.add(new ColorModel("Kenyan Copper color", "#6C322E"));
        colorList.add(new ColorModel("Goldie color", "#B39B69"));
        colorList.add(new ColorModel("Baker’s Chocolate color", "#5C3317"));
        colorList.add(new ColorModel("Gold Dust color", "#927748"));
        colorList.add(new ColorModel("Dynamite color", "#6F282B"));
        colorList.add(new ColorModel("Blast Yellow color", "#7E5B3F"));
        colorList.add(new ColorModel("Boomerang color", "#794E33"));
        colorList.add(new ColorModel("Coconut color", "#965A3E"));
        colorList.add(new ColorModel("Kobicha color", "#6B4423"));
        colorList.add(new ColorModel("Barley Corn color", "#A68B5B"));
        colorList.add(new ColorModel("Caramel color", "#AF6F09"));
        colorList.add(new ColorModel("Bracken color", "#4A2A04"));
        colorList.add(new ColorModel("Brazil color", "#815B28"));
        colorList.add(new ColorModel("Caput Mortuum color", "#592720"));
        colorList.add(new ColorModel("Tuscan Brown color", "#6F4E37"));
        colorList.add(new ColorModel("Ecru color", "#C2B280"));
        colorList.add(new ColorModel("Deep Brown color", "#410200"));
        colorList.add(new ColorModel("Bitter Chocolate color", "#9E5B40"));
        colorList.add(new ColorModel("Hawaiian Brown color", "#99522C"));
        colorList.add(new ColorModel("Brick color", "#9C661F"));
        colorList.add(new ColorModel("Brandy color", "#DCB68A"));
        colorList.add(new ColorModel("Chamoisee color", "#A0785A"));
        colorList.add(new ColorModel("Carnaby Tan color", "#5B3A24"));
        colorList.add(new ColorModel("Peru color", "#CD853F"));
        colorList.add(new ColorModel("Double Lumberjack color", "#633E36"));
        colorList.add(new ColorModel("Double Otter color", "#796053"));

        colorList.add(new ColorModel("Beige color", "#F5F5DC"));
        colorList.add(new ColorModel("Khaki color", "#C3B091"));
        colorList.add(new ColorModel("Almond color", "#EFDECD"));
        colorList.add(new ColorModel("Buttercream color", "#EFE0CD"));
        colorList.add(new ColorModel("Butter Toast color", "#D2AD84"));
        colorList.add(new ColorModel("Desert Gray color", "#B8A487"));
        colorList.add(new ColorModel("Beige Linen color", "#E2DAC6"));
        colorList.add(new ColorModel("Mojave Desert color", "#C7B595"));
        colorList.add(new ColorModel("Latte color", "#C5A582"));
        colorList.add(new ColorModel("Feather Brown color", "#B8AD9E"));
        colorList.add(new ColorModel("Fortune Cookie color", "#E0C5A1"));
        colorList.add(new ColorModel("Beaver color", "#9F8170"));
        colorList.add(new ColorModel("Wheat color", "#F5DEB3"));
        colorList.add(new ColorModel("Dark Vanilla color", "#D1BEA8"));
        colorList.add(new ColorModel("French Beige color", "#A67B50"));
        colorList.add(new ColorModel("Burlywood color", "#DEB887"));
        colorList.add(new ColorModel("Cashmere color", "#D1B399"));
        colorList.add(new ColorModel("Croissant color", "#C4AB86"));
        colorList.add(new ColorModel("Café Au Lait color", "#A67B5B"));
        colorList.add(new ColorModel("Wood brown color", "#C19A6B"));
        colorList.add(new ColorModel("Sand color", "#F6D7B0"));
        colorList.add(new ColorModel("Champagne color", "#FAD6A5"));
        colorList.add(new ColorModel("Froth Green color", "#CAC7B7"));
        colorList.add(new ColorModel("Gallery color", "#DCD7D1"));
        colorList.add(new ColorModel("Gargoyle color", "#907E69"));
        colorList.add(new ColorModel("Goldmine color", "#9B8160"));
        colorList.add(new ColorModel("Half Oilskin color", "#726459"));
        colorList.add(new ColorModel("Hampton color", "#E5D8AF"));
        colorList.add(new ColorModel("Haystack color", "#DEC7A1"));
        colorList.add(new ColorModel("Honey color", "#FCEDC5"));
        colorList.add(new ColorModel("Howlin Wolf color", "#B79F81"));
        colorList.add(new ColorModel("Incognito color", "#8E7C6E"));
        colorList.add(new ColorModel("Indian Khaki color", "#C3B091"));
        colorList.add(new ColorModel("Janna color", "#DED1B7"));
        colorList.add(new ColorModel("Joss color", "#B9A896"));
        colorList.add(new ColorModel("Kangaroo color", "#C5C3B0"));
        colorList.add(new ColorModel("Light French Beige color", "#C8AD7F"));
        colorList.add(new ColorModel("Fossil color", "#D5CBB2"));
        colorList.add(new ColorModel("Manilla color", "#D5C3AC"));
        colorList.add(new ColorModel("Matchstick color", "#C3B38D"));
        colorList.add(new ColorModel("Sanctuary color", "#A68459"));
        colorList.add(new ColorModel("Sandspit Brown color", "#D2C6B6"));
        colorList.add(new ColorModel("Bone color", "#E3DAC9"));

        colorList.add(new ColorModel("Acadia Color", "#1B1404"));
        colorList.add(new ColorModel("All Black Color", "#181818"));
        colorList.add(new ColorModel("Almost Black Color", "#070D0D"));
        colorList.add(new ColorModel("Asphalt Color", "#130A06"));
        colorList.add(new ColorModel("Aztec Color", "#0D1C19"));
        colorList.add(new ColorModel("Baltic Sea Color", "#2A2630"));
        colorList.add(new ColorModel("Banjul Color", "#130A06"));
        colorList.add(new ColorModel("Black Color", "#000000"));
        colorList.add(new ColorModel("Blackout Color", "#211916"));
        colorList.add(new ColorModel("Black Bean Color", "#081910"));
        colorList.add(new ColorModel("Black Leather Jacket Color", "#253529"));
        colorList.add(new ColorModel("Onyx Color", "#353839"));
        colorList.add(new ColorModel("Black Rock Color", "#0D0332"));
        colorList.add(new ColorModel("Black Russian Color", "#0A001C"));
        colorList.add(new ColorModel("Blue Bark Color", "#041322"));
        colorList.add(new ColorModel("Blue Charcoal Color", "#010D1A"));
        colorList.add(new ColorModel("Bunker Color", "#0D1117"));
        colorList.add(new ColorModel("Caffeine Color", "#3C3135"));
        colorList.add(new ColorModel("Cannon Black Color", "#251706"));
        colorList.add(new ColorModel("Chimney Sweep Color", "#1C1D1F"));
        colorList.add(new ColorModel("Cinder Color", "#0E0E18"));
        colorList.add(new ColorModel("Cod Gray Color", "#0B0B0B"));
        colorList.add(new ColorModel("Cyanish Black Color", "#1A1D1D"));
        colorList.add(new ColorModel("Double Barbecue Color", "#282020"));
        colorList.add(new ColorModel("Double Cod Gray Color", "#1D2020"));
        colorList.add(new ColorModel("Ebony Color", "#0C0B1D"));
        colorList.add(new ColorModel("Eerie Black Color", "#1B1B1B"));
        colorList.add(new ColorModel("Foundry Color", "#2C2E32"));
        colorList.add(new ColorModel("Gordons Green Color", "#0B1107"));
        colorList.add(new ColorModel("Green Waterloo Color", "#101405"));
        colorList.add(new ColorModel("Greenish Black Color", "#1A1D1A"));
        colorList.add(new ColorModel("Gray Color", "#000000"));
        colorList.add(new ColorModel("Gunmetal Color", "#020D15"));
        colorList.add(new ColorModel("Ivory Black Color", "#292421"));
        colorList.add(new ColorModel("Jacko Bean Color", "#2E1905"));
        colorList.add(new ColorModel("Jaguar Color", "#080110"));
        colorList.add(new ColorModel("Magentaish Black Color", "#1D1A1D"));
        colorList.add(new ColorModel("Maire Color", "#130A06"));
        colorList.add(new ColorModel("Marshland Color", "#0B0F08"));
        colorList.add(new ColorModel("Maxwell Smart Color", "#2A2525"));
        colorList.add(new ColorModel("Smoky Black Color", "#100C08"));


        colorList.add(new ColorModel("Gray color", "#808080"));
        colorList.add(new ColorModel("Ajay color", "#B0ACAE"));
        colorList.add(new ColorModel("Abbey color", "#495154"));
        colorList.add(new ColorModel("Silver color", "#C0C0C0"));
        colorList.add(new ColorModel("Charcoal color", "#36454F"));
        colorList.add(new ColorModel("Thunder color", "#BDB7AB"));
        colorList.add(new ColorModel("Antique White color", "#8B8378"));
        colorList.add(new ColorModel("Snow color", "#8B8989"));
        colorList.add(new ColorModel("Gray Owl color", "#D5D5CD"));
        colorList.add(new ColorModel("Carbon Gray color", "#625D5D"));
        colorList.add(new ColorModel("Gainsboro color", "#DCDCDC"));
        colorList.add(new ColorModel("Aquashield Half Tapa color", "#929288"));
        colorList.add(new ColorModel("Gray Dolphin color", "#5C5858"));
        colorList.add(new ColorModel("Ash Gray color", "#B2BEB5"));
        colorList.add(new ColorModel("Gray Goose color", "#D1D0CE"));
        colorList.add(new ColorModel("Avatar color", "#8B8F8E"));
        colorList.add(new ColorModel("Basalt color", "#524E50"));
        colorList.add(new ColorModel("Bombay color", "#AEAEAD"));
        colorList.add(new ColorModel("Tapa color", "#7B7874"));
        colorList.add(new ColorModel("Tasman color", "#BAC0B3"));
        colorList.add(new ColorModel("Boulder color", "#7A7A7A"));
        colorList.add(new ColorModel("Boulder color", "#7A7A7A"));
        colorList.add(new ColorModel("Cadet Gray color", "#91A3B0"));
        colorList.add(new ColorModel("Casper color", "#AAB5B8"));
        colorList.add(new ColorModel("Cathedral color", "#4B4D4A"));
        colorList.add(new ColorModel("Charcoal Gray color", "#3C4142"));
        colorList.add(new ColorModel("Chicago color", "#5B5D56"));
        colorList.add(new ColorModel("Chicane color", "#686765"));
        colorList.add(new ColorModel("Cobblestone color", "#807F73"));
        colorList.add(new ColorModel("Condor color", "#5B605C"));
        colorList.add(new ColorModel("Dark Greenish Gray color", "#535953"));
        colorList.add(new ColorModel("Dark Medium Gray color", "#A9A9A9"));
        colorList.add(new ColorModel("Dark Gray color", "#363737"));
        colorList.add(new ColorModel("Dark Olivish Gray color", "#595953"));
        colorList.add(new ColorModel("Davy’S Gray color", "#555555"));
        colorList.add(new ColorModel("Davy Gray color", "#555555"));
        colorList.add(new ColorModel("Delta color", "#999B95"));
        colorList.add(new ColorModel("Delta Gray color", "#A5A395"));
        colorList.add(new ColorModel("Detroit color", "#787774"));
        colorList.add(new ColorModel("Dim Gray color", "#545454"));
        colorList.add(new ColorModel("Dark Silver color", "#746D69"));
        colorList.add(new ColorModel("Dna color", "#333633"));
        colorList.add(new ColorModel("Double Concrete color", "#C5C5C3"));
        colorList.add(new ColorModel("Dusty Gray color", "#B29CA2"));
        colorList.add(new ColorModel("Double Friar Gray color", "#756F62"));
        colorList.add(new ColorModel("Graphite Gray color", "#4B4E53"));
        colorList.add(new ColorModel("Double Rakaia color", "#A9A5A5"));
        colorList.add(new ColorModel("Double Schooner color", "#726962"));
        colorList.add(new ColorModel("Rustic Gray color", "#A6ABA5"));
        colorList.add(new ColorModel("Double Surrender color", "#A8AAAB"));
        colorList.add(new ColorModel("Double Trojan color", "#656664"));
        colorList.add(new ColorModel("Dove Gray color", "#6D6C6C"));
        colorList.add(new ColorModel("Dusted Blue color", "#929FA2"));
        colorList.add(new ColorModel("Foggy Gray color", "#A7A69D"));
        colorList.add(new ColorModel("Silk Gray color", "#B6B3A8"));
        colorList.add(new ColorModel("White Gray color", "#F2F3F5"));
        colorList.add(new ColorModel("Agreeable Gray color", "#D1CBC1"));
        colorList.add(new ColorModel("Forcefield color", "#899694"));
        colorList.add(new ColorModel("Gentle Gray color", "#DADADA"));
        colorList.add(new ColorModel("Forecast color", "#A2AAB1"));
        colorList.add(new ColorModel("Battleship Gray color", "#848482"));
        colorList.add(new ColorModel("Freestyling color", "#A4A8B0"));
        colorList.add(new ColorModel("French Gray color", "#BDBDC6"));
        colorList.add(new ColorModel("Friar Gray color", "#807E79"));
        colorList.add(new ColorModel("Gannet Gray color", "#8E918F"));
        colorList.add(new ColorModel("Gauntlet color", "#716F69"));
        colorList.add(new ColorModel("Geyser color", "#CBD0CF"));
        colorList.add(new ColorModel("Sea Gray color", "#9AA2A4"));
        colorList.add(new ColorModel("Ghost color", "#C0BFC7"));
        colorList.add(new ColorModel("Gray Chateau color", "#9FA3A7"));
        colorList.add(new ColorModel("Gray Nurse color", "#D1D3CC"));
        colorList.add(new ColorModel("Chrome color", "#DBE2E9"));
        colorList.add(new ColorModel("Gray Suit color", "#9391A0"));
        colorList.add(new ColorModel("Dull Gray color", "#8B837E"));
        colorList.add(new ColorModel("Gunsmoke color", "#7A7C76"));
        colorList.add(new ColorModel("Half Tapa color", "#929288"));
        colorList.add(new ColorModel("Iron color", "#A59C94"));
        colorList.add(new ColorModel("Half Tasman color", "#D0D5CD"));
        colorList.add(new ColorModel("Half Taupe Gray color", "#9D998F"));
        colorList.add(new ColorModel("Half Truffle color", "#CDC9BE"));
        colorList.add(new ColorModel("Smokey Gray color", "#726E6D"));
        colorList.add(new ColorModel("Identity color", "#6E6767"));
        colorList.add(new ColorModel("Storm Gray color", "#B5BAB6"));
        colorList.add(new ColorModel("Imagine color", "#A39894"));
        colorList.add(new ColorModel("Ironside Gray color", "#676662"));
        colorList.add(new ColorModel("Nevada color", "#666A6D"));
        colorList.add(new ColorModel("Seal color", "#818380"));
        colorList.add(new ColorModel("Ivory color", "#8B8B83"));
        colorList.add(new ColorModel("Kensington Gray color", "#9D9F9A"));


        colorList.add(new ColorModel("Abalone color", "#D6CFC7"));
        colorList.add(new ColorModel("Light Gray color", "#D3D3D3"));
        colorList.add(new ColorModel("Medium Gray color", "#BEBEBE"));
        colorList.add(new ColorModel("Loblolly color", "#B3BBB7"));
        colorList.add(new ColorModel("Mercury color", "#D5D2D1"));
        colorList.add(new ColorModel("Timberwolf color", "#DBD7D2"));
        colorList.add(new ColorModel("Nickel color", "#727472"));
        colorList.add(new ColorModel("Manatee color", "#8D90A1"));
        colorList.add(new ColorModel("Meridian color", "#7C7E7E"));
        colorList.add(new ColorModel("Outer Space color", "#414A4C"));
        colorList.add(new ColorModel("Metro color", "#ACAFB1"));
        colorList.add(new ColorModel("Midwinter Mist color", "#CCCECE"));
        colorList.add(new ColorModel("Oslo Gray color", "#818988"));
        colorList.add(new ColorModel("Pastel Gray color", "#CFCFC4"));
        colorList.add(new ColorModel("Pink Gray color", "#E7DADA"));
        colorList.add(new ColorModel("Quick Silver color", "#A6A6A6"));
        colorList.add(new ColorModel("Roman Silver color", "#838996"));
        colorList.add(new ColorModel("Barely There color", "#DFDDD5"));
        colorList.add(new ColorModel("Rugged Lavender color", "#80818B"));
        colorList.add(new ColorModel("Scorpion color", "#5E5E5E"));
        colorList.add(new ColorModel("Seashell color", "#8B8682"));

// White Color Names
        colorList.add(new ColorModel("Alabaster color", "#F2F0E6"));
        colorList.add(new ColorModel("Old Wood color", "#F0EEE4"));
        colorList.add(new ColorModel("Azure Mist color", "#F0FFFF"));
        colorList.add(new ColorModel("Oyster White color", "#E3DFD2"));
        colorList.add(new ColorModel("Vista color", "#FDFCFA"));
        colorList.add(new ColorModel("Rice color", "#FAF5EF"));
        colorList.add(new ColorModel("Baby Powder color", "#FEFEFA"));
        colorList.add(new ColorModel("Floral color", "#FFFAF0"));
        colorList.add(new ColorModel("Bianca color", "#F4EFE0"));
        colorList.add(new ColorModel("Daisy color", "#FAFAFA"));
        colorList.add(new ColorModel("Bluish White color", "#F6F6FF"));
        colorList.add(new ColorModel("Milk color", "#FDFFF5"));
        colorList.add(new ColorModel("Natural White color", "#EEECE6"));
        colorList.add(new ColorModel("Powder color", "#FBFCFA"));
        colorList.add(new ColorModel("Old Lace color", "#FDF5E6"));
        colorList.add(new ColorModel("White Dove color", "#F0EFE7"));
        colorList.add(new ColorModel("Pearl color", "#FBFCF8"));
        colorList.add(new ColorModel("Catskill color", "#E0E4DC"));
        colorList.add(new ColorModel("Spring color", "#F3F0E8"));
        colorList.add(new ColorModel("Citrine White color", "#DEDDCB"));
        colorList.add(new ColorModel("Cyanish White color", "#F6FFFF"));
        colorList.add(new ColorModel("Coconut Butter color", "#F2EFE1"));
        colorList.add(new ColorModel("Designer White color", "#D7D9E2"));
        colorList.add(new ColorModel("White Whisper color", "#EAE8E1"));
        colorList.add(new ColorModel("Double Alabaster color", "#F3F3ED"));
        colorList.add(new ColorModel("Double Barely There color", "#E4E2D8"));
        colorList.add(new ColorModel("Eighth Ash color", "#E3E2DA"));
        colorList.add(new ColorModel("Bright White color", "#F4F5F0"));
        colorList.add(new ColorModel("Ghost color", "#F8F8FF"));
        colorList.add(new ColorModel("Glistening color", "#F4F4EC"));
        colorList.add(new ColorModel("Eggshell color", "#F0EAD6"));
        colorList.add(new ColorModel("Greenish White color", "#F6FFF6"));
        colorList.add(new ColorModel("Half Orchid White color", "#F7F4EA"));
        colorList.add(new ColorModel("Dutch White color", "#EFDFBB"));
        colorList.add(new ColorModel("Half Rice Cake color", "#F2F0E7"));
        colorList.add(new ColorModel("Half Sea Fog color", "#EFEEE7"));
        colorList.add(new ColorModel("Half White Pointer color", "#E2E1DB"));
        colorList.add(new ColorModel("Isabelline color", "#F4F0EC"));
        colorList.add(new ColorModel("Merino color", "#F2EBDD"));
        colorList.add(new ColorModel("Manyana color", "#F2F0E8"));
        colorList.add(new ColorModel("Marble color", "#E6E4D8"));
        colorList.add(new ColorModel("Porcelain color", "#DDDCDB"));
        colorList.add(new ColorModel("Promenade color", "#F8F6DF"));
        colorList.add(new ColorModel("Greek Villa color", "#F0EBE3"));
        colorList.add(new ColorModel("Saltpan color", "#EEF3E5"));
        colorList.add(new ColorModel("Simply White color", "#EFEDE3"));
        colorList.add(new ColorModel("Cough Mixture color", "#F6F4F1"));
        colorList.add(new ColorModel("Snow Drift color", "#E3E3DC"));
        colorList.add(new ColorModel("Soapstone color", "#ECE5DA"));




        return colorList;

    }



}
